# Generated by Django 3.0.4 on 2020-03-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=45)),
                ('customer_name', models.CharField(max_length=45)),
                ('customer_phonenumber', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
    ]
